name: example
description: Sample package demonstrating usage of Resolver Generator
version: 0.0.1
author: Sagar Gupta <sagarg@nurture.farm>

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  annotator:
    path: ../annotator

dev_dependencies:
  build_runner: ^2.4.0
  analysis_generator:
    path: ../analysis_generator


  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
