builders:
  single_builder:
    import: "package:analysis_generator/builder.dart"
    builder_factories: [ "analysisBuilder" ]
    build_extensions: { r'$lib$': [ "main.dart" ] }
    auto_apply: dependents
    build_to: source