name: analysis_generator
description: A dart package to generate map for resolvers
version: 0.0.1
author: Sagar Gupta <sagarg@nurture.farm>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.3.0
  build_config: ^0.4.0
  source_gen: ^0.9.0
  annotator:
    path: ../annotator/

dev_dependencies:
  test: ^1.6.0

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
