name: analysis_generator
description: A dart package to generate map for resolvers
version: 0.0.1
author: Sagar Gupta <sagarg@nurture.farm>

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.0
  build_config: ^1.0.0
  source_gen: ^1.4.0
  annotator:
    path: ../annotator/

dev_dependencies:
  test: ^1.6.0

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
